---
title: "DDI report template"
format: pdf
editor: source
---

```{r echo=F, warning=F, info=F, message=F}
library(tidyverse)
library(knitr)
# library(knitrdata)
library(ddir)

knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=TRUE, fig.width=4, fig.height=3, fig.align="center")
```

```{r ompound_data}
perp <- perpetrator(
  "examplinib",
  dose = 50, imaxss = 566, mw = 420.5, oral = TRUE, fu = 0.046, fa = 1,
  fg = 1, rb = 0.9, ka = 0.1,
  source = c(dose = "clinical dose", imaxss = "study 001", fu = "study 002",
             rb = "study 003")
)
```

```{r}
cyp_inh <- inhibitor(
  data = tribble(
    ~target, ~ki, ~source,
    "CYP2C9",  7.01,  "study 001",
    "CYP2C19", 48.7, "study 001",
    "CYP3A4",  100, "study 001"
  ),
  object = "examplinib"
)

ugt_inh <- inhibitor(
  data = tibble::tribble(
      ~target,  ~ki,     ~source,
     "UGT1A1",   15, "study 009",
     "UGT1A3",   15, "study 009",
     "UGT1A4",   15, "study 009",
     "UGT1A6",   15, "study 009",
     "UGT1A9",  3.8, "study 009",
     "UGT2B7",   15, "study 009",
    "UGT2B15",   15, "study 009",
    "UGT2B17",  6.1, "study 009",
  ),
  object = "examplinib"
)

transporter_inh <- inhibitor(
  data = tibble::tribble(
    ~target, ~ic50,     ~source,
      "Pgp",  0.41, "study 005",
     "BCRP",   1.9, "study 005",
     "OCT1",   2.3, "study 006",
  "OATP1B1",   177, "study 006",
  "OATP1B3",    35, "study 006",
     "OAT1",   271,          NA,
     "OAT3",   300,          NA,
     "BSEP",  12.8,          NA,
     "OCT2",    67, "study 006",
    "MATE1",   3.6, "study 006",
   "MATE2k",   1.1, "study 006"
  ),
  object = "examplinib"
)

cyp_tdi <- inhibitor(
  data = tibble::tribble(
    ~target, ~ki, ~kinact, ~source,
    "CYP3A4", 0.17,   0.04, "study 001"
  ),
  object = "examplinib"
)

cyp_ind <- inducer(
  data =tibble::tribble(
       ~target, ~emax, ~ec50, ~max_c,     ~source,
      "CYP1A2",     1,    NA,      5, "study 007",
      "CYP2B6",     1,    NA,      5, "study 007",
      "CYP2C8",    NA,    NA,     NA,          NA,
      "CYP2C9",    NA,    NA,     NA,          NA,
     "CYP2C19",    NA,    NA,     NA,          NA,
      "CYP2D6",    NA,    NA,     NA,          NA,
      "CYP3A4",  7.35,  1.64,      3, "study 007"
     ),
  object = "examplinib"
)
```

```{r}
print(perp)

key_conc(perp)

print(basic_cyp_inhibition_risk(perp, cyp_inh))
print(basic_ugt_inhibition_risk(perp, ugt_inh))
print(transporter_inh_risk(perp, transporter_inh))

print(basic_cyp_tdi_risk(perp, cyp_tdi))

print(static_cyp_induction_risk(perp, cyp_ind))
print(kinetic_cyp_induction_risk(perp, cyp_ind))

print(mech_stat_cyp_risk(perp, cyp_inh, cyp_ind, cyp_tdi))
print(mech_stat_cyp_risk(perp, cyp_inh, cyp_ind, cyp_tdi, include_induction = F))
```

